### ISSUE TITLE
Issue with running

### ISSUE THREAD

**Issue by KittenPixel** [ernesto-glz/discord-clone#4]
When I try to run this on my linux computer in the frontend i get this "GET http://localhost:3000/env-config.js net::ERR_ABORTED 404 (Not Found)" I am using mongo not docker

Here is logs of backend "[Nest] 59300  - 09/24/2023, 10:28:05 AM     LOG [NestFactory] Starting Nest application...
[Nest] 59300  - 09/24/2023, 10:28:05 AM     LOG [InstanceLoader] AuthModule dependencies initialized +14ms
[Nest] 59300  - 09/24/2023, 10:28:05 AM     LOG [InstanceLoader] ChannelsModule dependencies initialized +1ms
[Nest] 59300  - 09/24/2023, 10:28:05 AM     LOG [InstanceLoader] UsersModule dependencies initialized +0ms
[Nest] 59300  - 09/24/2023, 10:28:05 AM     LOG [InstanceLoader] RequestsModule dependencies initialized +0ms
[Nest] 59300  - 09/24/2023, 10:28:05 AM     LOG [InstanceLoader] AppModule dependencies initialized +0ms
10:09:00 warn: Some environment variables have not been declared.
10:09:01 error: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
[Nest] 59300  - 09/24/2023, 10:28:07 AM     LOG [RoutesResolver] AppController {/v1}: +1041ms
[Nest] 59300  - 09/24/2023, 10:28:07 AM     LOG [RouterExplorer] Mapped {/v1/upload, POST} route +2ms
[Nest] 59300  - 09/24/2023, 10:28:07 AM     LOG [RoutesResolver] AuthController {/v1/auth}: +0ms
[Nest] 59300  - 09/24/2023, 10:28:07 AM     LOG [RouterExplorer] Mapped {/v1/auth/login, POST} route +0ms
[Nest] 59300  - 09/24/2023, 10:28:07 AM     LOG [RouterExplorer] Mapped {/v1/auth/register, POST} route +1ms
[Nest] 59300  - 09/24/2023, 10:28:07 AM     LOG [RouterExplorer] Mapped {/v1/auth/change-username, PATCH} route +0ms
[Nest] 59300  - 09/24/2023, 10:28:07 AM     LOG [RouterExplorer] Mapped {/v1/auth/change-password, PATCH} route +1ms
[Nest] 59300  - 09/24/2023, 10:28:07 AM     LOG [RoutesResolver] UsersController {/v1/users}: +0ms
[Nest] 59300  - 09/24/2023, 10:28:07 AM     LOG [RouterExplorer] Mapped {/v1/users, DELETE} route +0ms
[Nest] 59300  - 09/24/2023, 10:28:07 AM     LOG [RouterExplorer] Mapped {/v1/users/entities, GET} route +0ms
[Nest] 59300  - 09/24/2023, 10:28:07 AM     LOG [RoutesResolver] ChannelsController {/v1/channels}: +0ms
[Nest] 59300  - 09/24/2023, 10:28:07 AM     LOG [RouterExplorer] Mapped {/v1/channels, POST} route +1ms
[Nest] 59300  - 09/24/2023, 10:28:07 AM     LOG [RouterExplorer] Mapped {/v1/channels/:channelId/messages, GET} route +0ms
[Nest] 59300  - 09/24/2023, 10:28:07 AM     LOG [RouterExplorer] Mapped {/v1/channels/:channelId/messages/:messageId, DELETE} route +1ms
[Nest] 59300  - 09/24/2023, 10:28:07 AM     LOG [RoutesResolver] RequestsController {/v1/requests}: +0ms
[Nest] 59300  - 09/24/2023, 10:28:07 AM     LOG [RouterExplorer] Mapped {/v1/requests, POST} route +0ms
[Nest] 59300  - 09/24/2023, 10:28:07 AM     LOG [RouterExplorer] Mapped {/v1/requests/:requestId, DELETE} route +0ms
[Nest] 59300  - 09/24/2023, 10:28:07 AM     LOG [RouterExplorer] Mapped {/v1/requests/:requestId, PUT} route +1ms
[Nest] 59300  - 09/24/2023, 10:28:07 AM     LOG [NestApplication] Nest application successfully started +1ms
10:09:04 info: API is running on port undefined
10:09:37 error: Cannot GET /
"

The cannot GET / is from me accessing it from browser and on browser it says 404. as well. mabye its the uri par causing the issue?

**Comment by KittenPixel** [comment]
I setup a .sh file to run but this is it and I was using this btw ``` 

MONGO_USER="" port=4000 MONGO_PASSWORD="" MONGO_UR=""
 yarn start:dev
``` I just put that stuff as blank for security.

**Comment by KittenPixel** [comment]
is that setup wrong?

**Comment by kik0desu** [comment]
> 10:09:04 info: API is running on port undefined

From what I see your environment variables are empty, I also recommend you check the docker configuration for development at `docker-compose.dev.yaml`, by following [this guide](https://github.com/ernesto-glz/discord-clone/tree/master#requirements) you should have no problems.

**Comment by KittenPixel** [comment]
How do I fix the env variables being empty as I don't use docker?

**Comment by KittenPixel** [comment]
btw I removed the env variables contents for security reasons when I sent it in the file used to run the server: ```MONGO_USER="" port=4000 MONGO_PASSWORD="" MONGO_UR=""
yarn start:dev
```

**Comment by kik0desu** [comment]
> How do I fix the env variables being empty as I don't use docker?

If you don't use docker then just create the `.env` files inside `frontend` and `backend` directories with the required environment variables (NOTE: for the backend you need to generate the jwt rsa file with the generate-keys.sh script), and then run it normally.

The environment variables for the backend should look like this:

```
PORT=4000
MONGO_URI=mongodb://<your_username>:<your_password>@127.0.0.1:27017/database-name?authSource=admin
MONGO_USER=your_username
MONGO_PASSWORD=your_username
```

![image](https://github.com/ernesto-glz/discord-clone/assets/80600689/8753d17a-516f-4ec6-80f6-359f1cc61fd0)

Edit: I forgot to say that in development mode the backend uses `dotenv`, which reads the `.env` file, I never tested setting environment variables at the script level or system level outside of docker.

**Comment by KittenPixel** [comment]
ok I will try this when I get home.

**Comment by KittenPixel** [comment]
for mongo uri can I use the mongoDB website DB?

**Comment by KittenPixel** [comment]
18:10:96 info: Connected to database mongodb+srv://<username>:<password>@------.wtsonof.mongodb.net/
The system cannot find the path specified. ????

**Comment by KittenPixel** [comment]
still [WS]: Connection to the server lost.

**Comment by KittenPixel** [comment]
[6:24:34 PM] Starting compilation in watch mode...

[6:24:36 PM] Found 0 errors. Watching for file changes.

[Nest] 9572  - 10/06/2023, 6:24:38 PM     LOG [NestFactory] Starting Nest application...
[Nest] 9572  - 10/06/2023, 6:24:38 PM     LOG [InstanceLoader] AuthModule dependencies initialized +20ms
[Nest] 9572  - 10/06/2023, 6:24:38 PM     LOG [InstanceLoader] ChannelsModule dependencies initialized +0ms
[Nest] 9572  - 10/06/2023, 6:24:38 PM     LOG [InstanceLoader] UsersModule dependencies initialized +1ms
[Nest] 9572  - 10/06/2023, 6:24:38 PM     LOG [InstanceLoader] RequestsModule dependencies initialized +0ms
[Nest] 9572  - 10/06/2023, 6:24:38 PM     LOG [InstanceLoader] AppModule dependencies initialized +0ms
18:10:96 info: Connected to database mongodb+srv://<username>:<password>@-------.wtsonof.mongodb.net/
The system cannot find the path specified.
[Nest] 9572  - 10/06/2023, 6:24:39 PM     LOG [RoutesResolver] AppController {/v1}: +962ms
[Nest] 9572  - 10/06/2023, 6:24:39 PM     LOG [RouterExplorer] Mapped {/v1/upload, POST} route +2ms
[Nest] 9572  - 10/06/2023, 6:24:39 PM     LOG [RoutesResolver] AuthController {/v1/auth}: +1ms
[Nest] 9572  - 10/06/2023, 6:24:39 PM     LOG [RouterExplorer] Mapped {/v1/auth/login, POST} route +0ms
[Nest] 9572  - 10/06/2023, 6:24:39 PM     LOG [RouterExplorer] Mapped {/v1/auth/register, POST} route +1ms
[Nest] 9572  - 10/06/2023, 6:24:39 PM     LOG [RouterExplorer] Mapped {/v1/auth/change-username, PATCH} route +0ms
[Nest] 9572  - 10/06/2023, 6:24:39 PM     LOG [RouterExplorer] Mapped {/v1/auth/change-password, PATCH} route +0ms
[Nest] 9572  - 10/06/2023, 6:24:39 PM     LOG [RoutesResolver] UsersController {/v1/users}: +1ms
[Nest] 9572  - 10/06/2023, 6:24:39 PM     LOG [RouterExplorer] Mapped {/v1/users, DELETE} route +0ms
[Nest] 9572  - 10/06/2023, 6:24:39 PM     LOG [RouterExplorer] Mapped {/v1/users/entities, GET} route +0ms
[Nest] 9572  - 10/06/2023, 6:24:39 PM     LOG [RoutesResolver] ChannelsController {/v1/channels}: +1ms
[Nest] 9572  - 10/06/2023, 6:24:39 PM     LOG [RouterExplorer] Mapped {/v1/channels, POST} route +0ms
[Nest] 9572  - 10/06/2023, 6:24:39 PM     LOG [RouterExplorer] Mapped {/v1/channels/:channelId/messages, GET} route +0ms
[Nest] 9572  - 10/06/2023, 6:24:39 PM     LOG [RouterExplorer] Mapped {/v1/channels/:channelId/messages/:messageId, DELETE} route +1ms
[Nest] 9572  - 10/06/2023, 6:24:39 PM     LOG [RoutesResolver] RequestsController {/v1/requests}: +0ms
[Nest] 9572  - 10/06/2023, 6:24:39 PM     LOG [RouterExplorer] Mapped {/v1/requests, POST} route +0ms
[Nest] 9572  - 10/06/2023, 6:24:39 PM     LOG [RouterExplorer] Mapped {/v1/requests/:requestId, DELETE} route +1ms
[Nest] 9572  - 10/06/2023, 6:24:39 PM     LOG [RouterExplorer] Mapped {/v1/requests/:requestId, PUT} route +0ms
[Nest] 9572  - 10/06/2023, 6:24:39 PM     LOG [NestApplication] Nest application successfully started +1ms
18:10:06 info: API is running on port 4000 NOTE: EDITED SO YOU DON'T KNOW MY MONGODB DB NAME. .env: MONGO_USER=------
MONGO_PASSWORD=------
MONGO_URI=mongodb+srv://<username>:<password>@DB_NAME_EDITED_SELF_EXPLAINATORY_WHY_EDITED.wtsonof.mongodb.net/
PORT=4000

Edit self explanatory.

**Comment by KittenPixel** [comment]
I will wait for reponse :)

**Comment by KittenPixel** [comment]
Oh ya and if it helps Im running it on windows.

**Comment by kik0desu** [comment]
> for mongo uri can I use the mongoDB website DB?

yes, you can

> still [WS]: Connection to the server lost.

check in the frontend environment variables that the websocket port is the API port + 1

> The system cannot find the path specified. ????

I'm pretty sure you haven't generated the ssh keys and when starting the server they can't be found, the ssh key is used to sign tokens

> Oh ya and if it helps Im running it on windows.

It doesn't matter where you are, I didn't do anything specific for Linux

**Comment by KittenPixel** [comment]
I generated SSH

**Comment by KittenPixel** [comment]
I can try again

**Comment by KittenPixel** [comment]
> I'm pretty sure you haven't generated the ssh keys and when starting the server they can't be found, the ssh key is used to sign tokens

Recreated SSH and still have the ```The system cannot find the path specified.```

**Comment by KittenPixel** [comment]
Still have: ```[WS]: Connection to the server lost.``` 

.env.dist: ```VITE_API_ROOT=http://localhost:4000
VITE_WS_ROOT=http://localhost:4001
VITE_API_VERSION=1  ```

**Comment by KittenPixel** [comment]
![image](https://github.com/ernesto-glz/discord-clone/assets/79544605/dd82a840-78e3-4412-8491-6123a5a75c03)
Backend folder

**Comment by kik0desu** [comment]
> ![image](https://user-images.githubusercontent.com/79544605/274089991-dd82a840-78e3-4412-8491-6123a5a75c03.png) Backend folder

In the screenshot i see a folder called -p, I think `mkdir -p`  doesn't work on windows or at least in the shell that u are using  https://github.com/ernesto-glz/discord-clone/blob/master/backend/src/main.ts#L53

You can try with
```js
import fs from 'fs';

...
...


fs.mkdir(resolve('./assets/upload'), { recursive: true });
```

Also check that the created ssh keys are inside the keys folder, I am not familiar with powershell or something like that, so i don't know if the scripts works correctly on Windows

**Comment by KittenPixel** [comment]
Do I add it under bootstrap?

**Comment by KittenPixel** [comment]
I see where

**Comment by KittenPixel** [comment]
testing now

**Comment by KittenPixel** [comment]
```src/main.ts:54:44 - error TS2345: Argument of type '{ recursive: boolean; }' is not assignable to parameter of type 'NoParamCallback'.
  Object literal may only specify known properties, and 'recursive' does not exist in type 'NoParamCallback'.

54     fs.mkdir(resolve('./assets/upload'), { recursive: true });
                                              ~~~~~~~~~~~~~~~

[7:23:46 PM] Found 1 error. Watching for file changes.
````

**Comment by KittenPixel** [comment]
C:\Users\Gamer\AppData\Roaming\npm/yarn start:dev I ran it like this since the normal yarn command broke.

**Comment by KittenPixel** [comment]
as well as almost every other command since my Path env variables broke

**Comment by KittenPixel** [comment]
aha Argument of type '{ recursive: boolean; }' is not assignable to parameter of type 'NoParamCallback'.
  Object literal may only specify known properties, and 'recursive' does not exist in type 'NoParamCallback'.ts(2345) I have no idea what to do

**Comment by KittenPixel** [comment]
Fixed just removed it and added the folder my self Backend: 
```[7:53:15 PM] File change detected. Starting incremental compilation...

[7:53:15 PM] Found 0 errors. Watching for file changes.

[Nest] 1656  - 10/30/2023, 7:53:17 PM     LOG [NestFactory] Starting Nest application...
[Nest] 1656  - 10/30/2023, 7:53:17 PM     LOG [InstanceLoader] AuthModule dependencies initialized +18ms
[Nest] 1656  - 10/30/2023, 7:53:17 PM     LOG [InstanceLoader] ChannelsModule dependencies initialized +0ms
[Nest] 1656  - 10/30/2023, 7:53:17 PM     LOG [InstanceLoader] UsersModule dependencies initialized +1ms
[Nest] 1656  - 10/30/2023, 7:53:17 PM     LOG [InstanceLoader] RequestsModule dependencies initialized +0ms
[Nest] 1656  - 10/30/2023, 7:53:17 PM     LOG [InstanceLoader] AppModule dependencies initialized +0ms
19:10:65 info: Connected to database mongodb+srv://<username>:<password>@chatbolt.wtsonof.mongodb.net/
[Nest] 1656  - 10/30/2023, 7:53:19 PM     LOG [RoutesResolver] AppController {/v1}: +1304ms
[Nest] 1656  - 10/30/2023, 7:53:19 PM     LOG [RouterExplorer] Mapped {/v1/upload, POST} route +2ms
[Nest] 1656  - 10/30/2023, 7:53:19 PM     LOG [RoutesResolver] AuthController {/v1/auth}: +0ms
[Nest] 1656  - 10/30/2023, 7:53:19 PM     LOG [RouterExplorer] Mapped {/v1/auth/login, POST} route +0ms
[Nest] 1656  - 10/30/2023, 7:53:19 PM     LOG [RouterExplorer] Mapped {/v1/auth/register, POST} route +1ms
[Nest] 1656  - 10/30/2023, 7:53:19 PM     LOG [RouterExplorer] Mapped {/v1/auth/change-username, PATCH} route +0ms
[Nest] 1656  - 10/30/2023, 7:53:19 PM     LOG [RouterExplorer] Mapped {/v1/auth/change-password, PATCH} route +1ms
[Nest] 1656  - 10/30/2023, 7:53:19 PM     LOG [RoutesResolver] UsersController {/v1/users}: +0ms
[Nest] 1656  - 10/30/2023, 7:53:19 PM     LOG [RouterExplorer] Mapped {/v1/users, DELETE} route +0ms
[Nest] 1656  - 10/30/2023, 7:53:19 PM     LOG [RouterExplorer] Mapped {/v1/users/entities, GET} route +1ms
[Nest] 1656  - 10/30/2023, 7:53:19 PM     LOG [RoutesResolver] ChannelsController {/v1/channels}: +0ms
[Nest] 1656  - 10/30/2023, 7:53:19 PM     LOG [RouterExplorer] Mapped {/v1/channels, POST} route +0ms
[Nest] 1656  - 10/30/2023, 7:53:19 PM     LOG [RouterExplorer] Mapped {/v1/channels/:channelId/messages, GET} route +1ms
[Nest] 1656  - 10/30/2023, 7:53:19 PM     LOG [RouterExplorer] Mapped {/v1/channels/:channelId/messages/:messageId, DELETE} route +0ms
[Nest] 1656  - 10/30/2023, 7:53:19 PM     LOG [RoutesResolver] RequestsController {/v1/requests}: +0ms
[Nest] 1656  - 10/30/2023, 7:53:19 PM     LOG [RouterExplorer] Mapped {/v1/requests, POST} route +0ms
[Nest] 1656  - 10/30/2023, 7:53:19 PM     LOG [RouterExplorer] Mapped {/v1/requests/:requestId, DELETE} route +1ms
[Nest] 1656  - 10/30/2023, 7:53:19 PM     LOG [RouterExplorer] Mapped {/v1/requests/:requestId, PUT} route +0ms
[Nest] 1656  - 10/30/2023, 7:53:19 PM     LOG [NestApplication] Nest application successfully started +1ms
19:10:10 info: API is running on port 4000```
--------------------------------------------------
Frontend: ```[WS]: Connection to the server lost.```

**Comment by KittenPixel** [comment]
The frontend env ```VITE_API_ROOT=http://localhost:4000
VITE_WS_ROOT=http://localhost:4001
VITE_API_VERSION=1  ```

**Comment by kik0desu** [comment]
> The frontend env `VITE_API_ROOT=http://localhost:4000 VITE_WS_ROOT=http://localhost:4001 VITE_API_VERSION=1 `

did u test with 127.0.0.1 instead of localhost ?, as far as i know windows do something weird when u use localhost, switches to ipv6 or something like that

**Comment by KittenPixel** [comment]
Still exact same and theres nothing extra saying stuff tried to connect 
![image](https://github.com/ernesto-glz/discord-clone/assets/79544605/1fff309d-558c-4bb2-ad2d-3254d592e136)

**Comment by KittenPixel** [comment]
![image](https://github.com/ernesto-glz/discord-clone/assets/79544605/8f4a0e7b-ebf9-49ad-a8e3-24460571f53c)
 Hmmmm I think I fonud everything.

**Comment by KittenPixel** [comment]
![image](https://github.com/ernesto-glz/discord-clone/assets/79544605/0e12cb70-4497-4edf-a94a-262cb154d846)

**Comment by KittenPixel** [comment]
Now its all of a sudden gone?

**Comment by KittenPixel** [comment]
time to setup env again.

**Comment by KittenPixel** [comment]
I will go to the Discord Clone preview site and copy it and edit the .env-config.js to see if it works.

**Comment by KittenPixel** [comment]
connection still lost.

**Comment by KittenPixel** [comment]
Also your demo site does this and is infinite loading.

![image](https://github.com/ernesto-glz/discord-clone/assets/79544605/6ae29145-f86f-4466-9e4c-c49b4b2d0e52)

**Comment by kik0desu** [comment]
env-config.js is only used in prod, in development mode it will not even be able to be loaded.
![image](https://github.com/ernesto-glz/discord-clone/assets/80600689/fab5573c-6a52-45bc-92a7-2ab652b59f6e)
I tried it on windows and it works perfectly

I just had to set `const isBrowserDevMode = true;` in `vite.config.ts` because powershell doesn't accept the way I'm passing BROWSER_DEV=true via CLI, and just run `yarn dev`

**Comment by KittenPixel** [comment]
That didn't fix it

**Comment by KittenPixel** [comment]
same with your link https://dclone-backend.nexus.ernestoglz.com I tried it

**Comment by KittenPixel** [comment]
btw I never got a vite thing.

**Comment by KittenPixel** [comment]
So ya I do put it into Prod it works.

**Comment by KittenPixel** [comment]
I just need a backend host now.

**Comment by KittenPixel** [comment]
On backend I get this WINDOWS ```15:11:07 error: Cannot GET /websocket/?EIO=4&transport=websocket```

**Comment by kik0desu** [comment]
> On backend I get this WINDOWS `15:11:07 error: Cannot GET /websocket/?EIO=4&transport=websocket`

That error doesn't give clear information, check that the backend is working correctly using postman, curl or some http client.
If everything works fine then check the frontend, but the truth is I don't understand why it gives you so many issues

**Comment by KittenPixel** [comment]
Whats a good test HTTP request?

**Comment by kik0desu** [comment]
> Whats a good test HTTP request?

It is determined by the status code returned by the request. You can see them here https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

**Comment by KittenPixel** [comment]
tried multiple httpclients Insomina gave this I don't remember the other ones ```Error: SSL connect error```

But a good like header to test as a send

**Comment by KittenPixel** [comment]
thats what I meant a good test header

**Comment by KittenPixel** [comment]
the 15:11:07 error: Cannot GET /websocket/?EIO=4&transport=websocket doesn't happen anymore btw. 

But still can't connect even with HTTP client.

**Comment by KittenPixel** [comment]
I tried using your backend for testing to see if it was frontend and it worked btw. I just need mine to work.

**Comment by KittenPixel** [comment]
hello?

**Comment by kik0desu** [comment]
@KittenPixel-cell I set up the backend on my local windows pc and it works correctly:
![image](https://github.com/ernesto-glz/discord-clone/assets/80600689/671c1855-a254-4a3f-b393-c096b494842e)
![image](https://github.com/ernesto-glz/discord-clone/assets/80600689/f35df26f-6605-41b1-a5e8-864d8cf29d9e)

This is the config for the requests using ws:
![image](https://github.com/ernesto-glz/discord-clone/assets/80600689/2bf26163-f1b2-452e-a15d-da7f2b534635)
![image](https://github.com/ernesto-glz/discord-clone/assets/80600689/eb33e46d-eeaa-4cf6-9e8b-7f3b8743c0e3)


This is the only change i made in the backend: `(main.ts)`
```ts
import 'dotenv/config';
import { NestFactory, Reflector } from '@nestjs/core';
import { AppModule } from './app.module';
import { connect } from 'mongoose';
import { AuthGuard } from './shared/auth.guard';
import { NestExpressApplication } from '@nestjs/platform-express';
import { join, resolve } from 'path';
import { ValidationPipe } from '@nestjs/common';
import { delay } from './utils/utilts';
import { execSync } from 'child_process';
import helmet from 'helmet';
import './modules/logger';
import './modules/app';
import { mkdirSync } from 'fs';

async function bootstrap() {
  const app = await NestFactory.create<NestExpressApplication>(AppModule);
  const isProd = process.env.NODE_ENV === 'production';
  const reflector = app.get(Reflector);

  app.enableCors({ origin: '*' });
  app.setGlobalPrefix('v1');
  app.useGlobalGuards(new AuthGuard(reflector));
  app.useGlobalPipes(new ValidationPipe());
  app.use(helmet.xssFilter());
  app.use(helmet.noSniff());
  app.use(helmet.hidePoweredBy());
  app.use(helmet.frameguard({ action: 'deny' }));
  app.useStaticAssets(join(__dirname, '../assets'), { prefix: '/assets' });

  // Temp fix hot reload broke ws-sessions (only for development)
  !isProd && (await delay(1000));

  if (!process.env.MONGO_URI) {
    logger.warn('Some environment variables have not been declared.');
  }

  try {
    const config = isProd ?  {
      authSource: 'admin',
      auth: {
        username: process.env.MONGO_USER,
        password: process.env.MONGO_PASSWORD
      }
    } : {};
    await connect(process.env.MONGO_URI, config)
    logger.info(`Connected to database ${process.env.MONGO_URI}`);
  } catch (error) {
    logger.error(error.message ?? 'Unable to connect to db')
  }

  mkdirSync(resolve('./assets/upload'), { recursive: true });

  await app
    .listen(process.env.PORT ?? 4000)
    .then(() => logger.info(`API is running on port ${process.env.PORT}`))
    .catch((error) => logger.error(error));
}
bootstrap();
```
from
```ts
  try {
     execSync(`mkdir -p $ ${resolve('./assets/upload')} 2>> /dev/null`);
  } catch {}
```
to
```ts
mkdirSync(resolve('./assets/upload'), { recursive: true });
```

and ofc it works with the frontend
![image](https://github.com/ernesto-glz/discord-clone/assets/80600689/26e80acf-0913-4bb8-a737-871568d6b15d)
![image](https://github.com/ernesto-glz/discord-clone/assets/80600689/1d4c7798-302c-4981-beab-c9ee5826039f)

**Comment by kik0desu** [comment]
also your environment variables should look like this
![image](https://github.com/ernesto-glz/discord-clone/assets/80600689/57cdf8f7-8333-4f02-8a2b-3a6544deaf9a)
![image](https://github.com/ernesto-glz/discord-clone/assets/80600689/919c98a1-aa02-4f54-9c2a-05b163ec148c)

**Comment by KittenPixel** [comment]
Thats good 
![image](https://github.com/ernesto-glz/discord-clone/assets/79544605/4a7ce196-9178-4725-b7b1-f310f2304254)
For Env Vars
![image](https://github.com/ernesto-glz/discord-clone/assets/79544605/47189ed6-0073-49af-ba9a-4601ff5de986)
They were already that

**Comment by KittenPixel** [comment]
wait nvm

**Comment by KittenPixel** [comment]
![image](https://github.com/ernesto-glz/discord-clone/assets/79544605/eeefcb99-7ac9-4697-ba5d-8611eb3f3804)
altough the .js one was good.

**Comment by KittenPixel** [comment]
Still getting SSL COnnecte error

**Comment by kik0desu** [comment]
> Still getting SSL COnnecte error

I don't know what problem your setup might have, I've tried everything I could and it just works for me, I'm sorry but I can't do anything else

**Comment by KittenPixel** [comment]
I just noticed what the SSL connect error is now that I do APIs. I didn't have any SSL certificates and I was trying to use HTTPS. I don't need this anymore just letting you know for helping future people.
